version: "3.8"

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: guac-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:     ${MYSQL_DATABASE}
      MYSQL_USER:         ${MYSQL_USER}
      MYSQL_PASSWORD:     ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - guac-db-data:/var/lib/mysql
      - initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - guacnet

  guacd:
    image: guacamole/guacd:${GUACAMOLE_VERSION}
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole:${GUACAMOLE_VERSION}
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - mysql
      - guacd
    environment:
      MYSQL_ENABLED:   "true"
      MYSQL_HOSTNAME:  mysql
      MYSQL_PORT:      3306
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_USERNAME:  ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      GUACD_HOSTNAME:  guacd
    volumes:
      - initdb:/opt/guacamole/extensions/guacamole-auth-jdbc/mysql/schema:ro
    networks:
      - guacnet

  proxy:
    image: nginx:stable-alpine
    container_name: guac-proxy
    restart: unless-stopped
    depends_on:
      - guacamole
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - guacnet

volumes:
  guac-db-data:
  initdb:

networks:
  guacnet:
    driver: bridge

